apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-seconddb
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: postgres-seconddb
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        command: ["createdb"]
        args: ["-h","20.69.73.40", "-U", "postgresadmin", "db2" ]
        envFrom:
          - configMapRef:
              name: dbcreate-script2
      restartPolicy: Never