apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermgmt-webapp
spec:
  selector:
    matchLabels:
      app: usermgmt-webapp
  template:
    metadata:
      labels:
        app: usermgmt-webapp
    spec:
      # virtual nodes does not support init containers
      # initContainers:
      # - name: init-db
      #   image: busybox:1.31
      #   command: ['sh', '-c', 'echo -e "checking for availability of mysql server deployment"; while !nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e ">> mysql db server has started";']
      containers:
      - name: usermgmt-webapp
        image: stacksimplify/kube-usermgmt-webapp:1.0.0-MySQLDB
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8080
        env:
          - name: DB_HOSTNAME
            value: "mysql.default.svc.cluster.local"
          - name: DB_PORT
            value: "3306"
          - name: "DB_NAME"
            value: "webappdb"
          - name: DB_USERNAME
            value: "root"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-db-password
                key: dbpassword
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule