apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-standard-retain-sc
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain # default is delete
volumeBindingMode: WaitForFirstConsumer # default is immediate. 
allowVolumeExpansion: true 
parameters:
  storageaccounttype: Standard_LRS
  kind: managed
